name: Output Info
on:
  issues:
    types: [opened]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          gh issue --repo ${{ github.repository }} \
          create --title "Issue title" --body "Issue body"
